import { Destination } from './types'

export const destinations: Destination[] = [
    {
        id: 'paris-1889',
        title: 'Paris 1889',
        period: 'Belle Époque',
        tagline: 'L\'inauguration de la Tour Eiffel',
        image: '/destinations/paris-1889.jpg',
        description: 'Voyagez au cœur de la Belle Époque et assistez à l\'inauguration de la Tour Eiffel lors de l\'Exposition Universelle de 1889. Promenez-vous sur les Champs-Élysées, découvrez le Paris des impressionnistes et côtoyez les artistes et intellectuels de l\'époque.',
        highlights: [
            'Inauguration de la Tour Eiffel par Gustave Eiffel',
            'Visite de l\'Exposition Universelle de 1889',
            'Dîner au Maxim\'s dans son ambiance d\'origine',
            'Spectacle au Moulin Rouge avec les cancanières',
            'Rencontre avec les impressionnistes à Montmartre',
            'Balade en calèche dans le Bois de Boulogne',
        ],
        bestFor: [
            'Amateurs d\'art et d\'architecture',
            'Passionnés d\'histoire française',
            'Couples en quête de romantisme',
            'Amoureux de la gastronomie raffinée',
        ],
        safetyNotes: [
            'Époque politiquement stable et sûre',
            'Hygiène publique en amélioration',
            'Accompagnement francophone garanti',
            'Vaccinations recommandées (typhus, variole)',
        ],
        riskLevel: 'Faible',
        toAvoid: [
            'Les quartiers périphériques après la tombée de la nuit',
            'L\'eau non bouillie',
            'Les discussions politiques sensibles (affaire Boulanger)',
        ],
        recommendedDuration: '5 à 7 jours',
        packages: [
            {
                name: 'Découverte',
                price: '12 500 €',
                features: [
                    'Transport temporel aller-retour',
                    'Hôtel 3 étoiles Belle Époque',
                    '3 repas par jour',
                    'Guide historique',
                    'Garde-robe d\'époque',
                    'Visite de la Tour Eiffel',
                ],
            },
            {
                name: 'Prestige',
                price: '28 900 €',
                features: [
                    'Transport temporel premium',
                    'Suite au Grand Hôtel',
                    'Gastronomie étoilée',
                    'Guide privé multilingue',
                    'Garde-robe sur mesure',
                    'Accès VIP Exposition Universelle',
                    'Spectacle au Moulin Rouge',
                    'Rencontre avec artiste célèbre',
                ],
            },
            {
                name: 'Impérial',
                price: '59 000 €',
                features: [
                    'Transport temporel suite privée',
                    'Appartement privé Avenue Foch',
                    'Chef personnel',
                    'Majordome et équipe dédiée',
                    'Couturier personnel',
                    'Accès coulisses Exposition',
                    'Dîner avec personnalités de l\'époque',
                    'Atelier privé avec impressionniste',
                    'Voiture de collection avec chauffeur',
                ],
            },
        ],
    },
    {
        id: 'cretaceous',
        title: 'Crétacé -65M',
        period: 'Mésozoïque',
        tagline: 'À l\'aube de l\'extinction',
        image: '/destinations/cretaceous.jpg',
        description: 'Plongez 65 millions d\'années en arrière, à l\'époque des derniers dinosaures. Observez des Tyrannosaurus Rex, des Tricératops et des Ptéranodons dans leur habitat naturel. Une aventure extraordinaire dans un monde préhistorique luxuriant, juste avant l\'impact météoritique qui changera le cours de l\'histoire.',
        highlights: [
            'Observation sécurisée de T-Rex et Tricératops',
            'Safari préhistorique en véhicule blindé',
            'Survol en montgolfière au-dessus de la canopée',
            'Découverte de flore endémique',
            'Observation d\'un troupeau de titanosaures',
            'Nuit sous les étoiles (avec protection renforcée)',
        ],
        bestFor: [
            'Passionnés de paléontologie',
            'Aventuriers expérimentés',
            'Amoureux de la nature sauvage',
            'Photographes animaliers',
        ],
        safetyNotes: [
            'Équipement de protection avancée obligatoire',
            'Accompagnement par experts paléontologues',
            'Véhicules blindés certifiés anti-prédateurs',
            'Zone d\'observation sécurisée à distance',
            'Balise de secours temporelle individuelle',
        ],
        riskLevel: 'Élevé',
        toAvoid: [
            'S\'éloigner du périmètre de sécurité',
            'Faire du bruit excessif',
            'Approcher les nids de dinosaures',
            'Toucher la faune ou la flore',
            'Sortir du véhicule sans autorisation',
        ],
        recommendedDuration: '3 à 4 jours',
        packages: [
            {
                name: 'Découverte',
                price: '45 000 €',
                features: [
                    'Transport temporel sécurisé',
                    'Campement fortifié 5 étoiles',
                    'Repas gastronomiques',
                    'Guide paléontologue expert',
                    'Équipement de protection complet',
                    'Safari terrestre (2 sorties)',
                    'Assurance temporelle renforcée',
                ],
            },
            {
                name: 'Prestige',
                price: '89 000 €',
                features: [
                    'Transport temporel VIP',
                    'Dôme panoramique privatif',
                    'Chef étoilé et sommelier',
                    'Équipe scientifique dédiée',
                    'Combinaison haute technologie',
                    'Safari illimité (terre et air)',
                    'Survol en montgolfière',
                    'Documentaire personnalisé 4K',
                ],
            },
            {
                name: 'Impérial',
                price: '199 000 €',
                features: [
                    'Transport temporel suite luxe',
                    'Base scientifique privée',
                    'Équipe complète (chef, médecin, scientifiques)',
                    'Combinaison sur mesure',
                    'Accès zones exclusives',
                    'Hélicoptère temporel privé',
                    'Observation rapprochée supervisée',
                    'Hologramme souvenir 3D',
                    'Certificat de découverte paléontologique',
                ],
            },
        ],
    },
    {
        id: 'florence-1504',
        title: 'Florence 1504',
        period: 'Renaissance',
        tagline: 'Au sommet de la Renaissance',
        image: '/destinations/florence-1504.jpg',
        description: 'Découvrez Florence au zénith de la Renaissance italienne. Rencontrez Michel-Ange travaillant sur son David, croisez Léonard de Vinci, et plongez dans l\'effervescence artistique et intellectuelle de cette époque dorée. Les Médicis règnent sur la cité, et l\'art est roi.',
        highlights: [
            'Atelier de Michel-Ange et découverte du David',
            'Rencontre avec Léonard de Vinci',
            'Visite privée du Palazzo Vecchio',
            'Fresques de la Chapelle Brancacci',
            'Banquet Renaissance au Palazzo Strozzi',
            'Promenade sur le Ponte Vecchio historique',
        ],
        bestFor: [
            'Amateurs d\'art et d\'histoire de l\'art',
            'Passionnés de Renaissance',
            'Intellectuels et philosophes',
            'Collectionneurs et mécènes',
        ],
        safetyNotes: [
            'Période relativement stable à Florence',
            'Respect strict du protocole Médicis',
            'Formation culturelle préalable incluse',
            'Traducteur italien ancien fourni',
            'Vêtements d\'époque obligatoires',
        ],
        riskLevel: 'Modéré',
        toAvoid: [
            'Les rivalités politiques entre familles',
            'Critiquer l\'Église ou les Médicis',
            'Porter des couleurs des familles rivales',
            'Exhiber des technologies modernes',
            'S\'aventurer seul dans les ruelles sombres',
        ],
        recommendedDuration: '6 à 8 jours',
        packages: [
            {
                name: 'Découverte',
                price: '18 500 €',
                features: [
                    'Transport temporel aller-retour',
                    'Palazzo historique restauré',
                    'Cuisine toscane authentique',
                    'Guide historien de l\'art',
                    'Garde-robe Renaissance',
                    'Visite des ateliers d\'artistes',
                    'Cours de latin et d\'italien ancien',
                ],
            },
            {
                name: 'Prestige',
                price: '42 000 €',
                features: [
                    'Transport temporel premium',
                    'Suite au Palazzo Pitti',
                    'Banquets Renaissance',
                    'Historien d\'art privé',
                    'Costumes sur mesure de maître',
                    'Rencontre avec Michel-Ange',
                    'Atelier peinture avec maître Renaissance',
                    'Concert privé de musique ancienne',
                ],
            },
            {
                name: 'Impérial',
                price: '95 000 €',
                features: [
                    'Transport temporel suite royale',
                    'Appartements privés Médicis',
                    'Chef Renaissance personnel',
                    'Équipe dédiée multilingue',
                    'Garde-robe princière complète',
                    'Audience privée avec les Médicis',
                    'Commande d\'œuvre à Michel-Ange (réplique)',
                    'Soirée privée Palazzo Vecchio',
                    'Manuscrit enluminé personnalisé',
                ],
            },
        ],
    },
]
